services:
  - type: web
    name: stock-lstm-api
    env: docker
    dockerfilePath: ./Dockerfile.prod
    plan: starter
    startCommand: uvicorn app.main:app --host=0.0.0.0 --port=$PORT
    autoDeploy: true
    envVars:
      - key: ENVIRONMENT
        value: prod
      - key: DEBUG
        value: "False"
